'use client';

import {useEffect, useState} from 'react';
import {ArrowDownToLine, ArrowLeft, ArrowRight, Check, ChevronRight, CircleHelp, Database, FileSpreadsheet, FileText, FolderOpen, LayoutDashboard, LockKeyhole, Mail, Moon, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Sun, Users, Wallet, X, Upload, RefreshCw, LoaderCircle, Download, Building2, History} from 'lucide-react';

type Row = Record<string, any>;
type Native = {choose:(purpose:string, name:string, callback:(result:string)=>void)=>void; openSaved:(ticket:string, callback:(ok:boolean)=>void)=>void};
declare global {interface Window {payrollToken:string; nativeReady:Promise<Native>; desktop:Native; payrollDirty:boolean; payrollBusy:boolean}}
const money = (n:number=0) => new Intl.NumberFormat('en-PK', {maximumFractionDigits:0}).format(n);
const monthLabel = (m:string) => new Date(m+'-02T12:00:00').toLocaleDateString('en', {month:'long',year:'numeric'});
const nav = [{name:'Dashboard',icon:LayoutDashboard},{name:'Employees',icon:Users},{name:'Payroll',icon:Wallet},{name:'Reports',icon:FileText},{name:'Settings',icon:Settings2}];
const reportTypes = [
  {kind:'pdf', title:'Employee payslips', desc:'One polished A4 payslip per employee, together in a PDF.',ext:'pdf',icon:FileText,tag:'PDF'},
  {kind:'salary',title:'Salary register',desc:'Complete earnings, deductions and net pay with Excel totals.',ext:'xlsx',icon:FileSpreadsheet,tag:'EXCEL'},
  {kind:'bank',title:'Bank transfer statement',desc:'Employee names, account details and amounts for your bank.',ext:'xlsx',icon:Building2,tag:'EXCEL'},
  {kind:'cpf',title:'CPF statement',desc:'Employee and college contributions, plus loan instalments.',ext:'xlsx',icon:ShieldCheck,tag:'EXCEL'},
  {kind:'word',title:'Bank details document',desc:'An editable document containing salary transfer details.',ext:'docx',icon:FileText,tag:'WORD'},
];
const payFields = [['basic','Running basic'],['hr','House rent'],['conv','Conveyance'],['medl','Medical'],['adhoc','Adhoc allowance'],['spec','Special allowance'],['arrear','Arrears / encashment'],['cpf','CPF deduction'],['cp_loan','Loan instalment'],['other','Other deduction']];

async function api(path:string, method='GET', body?:unknown) {
  if (!window.nativeReady) throw new Error('Open Payroll Desk through its desktop shortcut.');
  await window.nativeReady;
  const result=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-Payroll-Token':window.payrollToken},body:body===undefined?undefined:JSON.stringify(body)});
  const data=await result.json().catch(()=>({detail:'The local service could not complete this operation. Please retry or restart Payroll Desk.'}));
  if(!result.ok) throw new Error(Array.isArray(data.detail)?data.detail.map((d:Row)=>`${d.loc?.slice(1).join('.')}: ${d.msg}`).join('\n'):data.detail || 'Something went wrong. Please try again.');
  return data;
}
async function choose(purpose:string,name='') {
  const native=await window.nativeReady;
  return new Promise<Row>((resolve,reject)=>native.choose(purpose,name,text=>{const result=JSON.parse(text);if(result.error)reject(new Error(result.error));else resolve(result)}));
}

export default function Home() {
  const [page,setPage]=useState('Dashboard');
  const [theme,setTheme]=useState('light');
  const [month,setMonth]=useState('');
  const [months,setMonths]=useState<string[]>([]);
  const [rows,setRows]=useState<Row[]>([]);
  const [employees,setEmployees]=useState<Row[]>([]);
  const [scales,setScales]=useState<Row[]>([]);
  const [settings,setSettings]=useState<Row>({});
  const [labels,setLabels]=useState<Row>({});
  const [directory,setDirectory]=useState('');
  const [locked,setLocked]=useState(false);
  const [query,setQuery]=useState('');
  const [selected,setSelected]=useState<number[]>([]);
  const [busy,setBusy]=useState('');
  const [notice,setNotice]=useState<{text:string,error?:boolean,open?:string}|null>(null);
  const [editor,setEditor]=useState<{kind:string,data:Row}|null>(null);
  const [dirty,setDirty]=useState(false);
  const [settingsDirty,setSettingsDirty]=useState(false);
  const [settingsTab,setSettingsTab]=useState('General');
  const [scope,setScope]=useState('all');
  const [includeInactive,setIncludeInactive]=useState(false);
  const [sort,setSort]=useState({key:'name',asc:true});
  const [ready,setReady]=useState(false);

  useEffect(()=>{window.payrollDirty=dirty||settingsDirty;},[dirty,settingsDirty]);
  useEffect(()=>{window.payrollBusy=Boolean(busy)},[busy]);
  useEffect(()=>{window.scrollTo(0,0)},[page,ready]);
  useEffect(()=>{
    const saved=localStorage.getItem('payroll-theme')||'light';setTheme(saved);document.documentElement.dataset.theme=saved;
    const now=new Date();const current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
    setMonth(current);void run('Opening your workspace',async()=>{await refresh(current,true);setReady(true)});
  },[]);

  async function run(label:string, action:()=>Promise<void>) {setBusy(label);setNotice(null);try{await action()}catch(error){setNotice({text:error instanceof Error?error.message:String(error),error:true})}finally{setBusy('')}}
  async function refresh(m=month,bootstrap=false) {
    const [pay,staff,bps]=await Promise.all([api('/payroll/'+m),api('/employees'),api('/scales')]);
    setRows(pay.rows);setLocked(pay.locked);setEmployees(staff);setScales(bps);
    if(bootstrap){const boot=await api('/bootstrap');setSettings(boot.settings);setLabels(boot.labels);setMonths(boot.months);setDirectory(boot.data_directory);setSettingsDirty(false)}
  }
  function changePage(name:string){if(editor&&!closeEditor())return;if(settingsDirty&&name!=='Settings'&&!confirm('Settings have unsaved changes. Leave without saving?'))return;if(settingsDirty&&name!=='Settings'){setSettingsDirty(false);void api('/bootstrap').then(b=>setSettings(b.settings))}setPage(name);setQuery('')}
  function closeEditor(){if(dirty&&!confirm('Discard unsaved changes?'))return false;setEditor(null);setDirty(false);return true}
  function openEditor(kind:string,data:Row){if(editor&&!closeEditor())return;setEditor({kind,data:{...data}});setDirty(false)}
  function edit(key:string,value:any){setEditor(e=>e?{...e,data:{...e.data,[key]:value}}:null);setDirty(true)}
  async function switchMonth(m:string){if(!/^\d{4}-\d{2}$/.test(m))return;if(editor&&!closeEditor())return;await run('Loading payroll',async()=>{await refresh(m);setMonth(m);setSelected([])})}
  function toggleTheme(){const next=theme==='light'?'dark':'light';setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem('payroll-theme',next)}
  async function saveEditor(){if(!editor)return;await run('Saving changes',async()=>{
    let data={...editor.data};
    if(editor.kind==='employee'){
      for(const k of ['basic','special','cpf_member','active'])data[k]=Number(data[k]??(k==='active'||k==='cpf_member'?1:0));data.bps=data.bps===''||data.bps==null?null:Number(data.bps);
      await api('/employees'+(data.id?'/'+data.id:''),data.id?'PUT':'POST',data);
    } else if(editor.kind==='pay') {
      for(const k of [...payFields.map(f=>f[0]),'wd','worked','cpf_member'])data[k]=Number(data[k]??0);data.bps=data.bps===''||data.bps==null?null:Number(data.bps);
      await api(`/payroll/${month}/${data.emp_id}`,'PUT',data);
    } else {for(const k of ['bps','hr','conv','medl','adhoc','cpf'])data[k]=Number(data[k]||0);await api('/scales','POST',data)}
    setEditor(null);setDirty(false);await refresh();setNotice({text:'Changes saved successfully.'});
  })}
  async function report(kind:string){const config=reportTypes.find(r=>r.kind===kind)!;if(scope==='selected'&&!selected.length){setNotice({text:'Select employees on the Payroll screen first.',error:true});return}await run('Preparing '+config.title.toLowerCase(),async()=>{
    const pick=await choose('export',`${config.title.replaceAll(' ','_')}_${month}_${locked?'Final':'Draft'}.${config.ext}`);if(pick.cancelled)return;
    const result=await api('/export','POST',{ticket:pick.ticket,kind,month,ids:scope==='selected'?selected:[]});setNotice({text:'Saved to '+result.path,open:result.open_ticket});
  })}
  async function importWorkbook(){if(!confirm('Import a college salary workbook? Matching employees and BPS scales will be updated. An automatic database backup will be created.'))return;await run('Importing workbook',async()=>{const pick=await choose('import');if(pick.cancelled)return;const rep=await api('/import','POST',{ticket:pick.ticket});const m=`${rep.year}-${String(rep.month).padStart(2,'0')}`;setMonth(m);await refresh(m,true);setPage('Payroll');setSelected([]);setNotice({text:`Imported ${rep.total} records: ${rep.added} new, ${rep.updated} updated. ${rep.unmatched.length} without matched bank details; ${rep.loose.length} similar-name matches to review. ${rep.model_gaps.length} allowance differences. ${rep.adjustments.length} other deductions.`+(rep.loose.length?'\nReview matches: '+rep.loose.map((x:string[])=>x.join(' ↔ ')).join(', '):'')+(rep.unmatched.length?'\nMissing bank matches: '+rep.unmatched.join(', '):'')})})}
  async function lockMonth(){if(!confirm(locked?'Unlock this month? Salaries will recalculate using current master data and monthly inputs.':'Finalize and lock this month? Review salary amounts before continuing.'))return;await run(locked?'Unlocking month':'Locking month',async()=>{await api(`/payroll/${month}/${locked?'unlock':'lock'}`,'POST');await refresh();setNotice({text:locked?'Month unlocked. Payroll has been recalculated.':'Month locked. Salary figures are now preserved.'})})}
  async function backup(){await run('Creating database backup',async()=>{const pick=await choose('backup',`Payroll_Backup_${new Date().toISOString().slice(0,10)}.db`);if(pick.cancelled)return;const result=await api('/backup','POST',{ticket:pick.ticket});setNotice({text:'Backup saved to '+result.path})})}
  async function restore(){if(!confirm('Restore replaces current payroll data. A safety backup will be created first. Continue?'))return;await run('Restoring backup',async()=>{const pick=await choose('restore');if(pick.cancelled)return;await api('/restore','POST',{ticket:pick.ticket});await refresh(month,true);setSelected([]);setNotice({text:'Backup restored successfully. Your previous database is in the backups folder.'})})}
  async function sendEmail(){if(!confirm(`Send ${monthLabel(month)} payslips to all ${rows.filter(r=>r.email).length} employees with an email address? An internet connection and SMTP settings are required.`))return;await run('Sending payslips — please keep the app open',async()=>{const r=await api('/email','POST',{month});setNotice({text:`Sent: ${r.sent.length}. Skipped or failed: ${r.skipped.length}.`+(r.skipped.length?'\n'+r.skipped.join('\n'):'')})})}
  const totals=rows.reduce((a,r)=>({gross:a.gross+r.gross,net:a.net+r.net,ded:a.ded+r.gross-r.net}),{gross:0,net:0,ded:0});
  const shown=(page==='Employees'?employees.filter(e=>includeInactive||e.active):rows).filter(r=>[r.name,r.designation,r.des,r.bps].some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{const x=a[sort.key],y=b[sort.key];return(typeof x==='number'?x-y:String(x??'').localeCompare(String(y??'')))*(sort.asc?1:-1)});
  const toggleSort=(key:string)=>setSort(s=>({key,asc:s.key===key?!s.asc:true}));
  const issueCount=rows.filter(r=>r.net<0||!r.acct||!r.bank).length;
  const formInput=(key:string,label:string,type='text',options?:{min?:number,max?:number})=><label className="field" key={key}><span>{label}</span><input type={type} value={editor?.data[key]??''} onChange={e=>edit(key,e.target.value)} {...options}/></label>;

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Wallet size={23}/></div><div>Payroll<span>DESK · LOCAL WORKSPACE</span></div></div>
      <div className="nav-label">WORKSPACE</div>
      <nav>{nav.map(({name,icon:Icon})=><button key={name} className={page===name?'nav-item active':'nav-item'} onClick={()=>changePage(name)}><Icon size={19}/><span>{name}</span>{page===name&&<ChevronRight size={15}/>}</button>)}</nav>
      <div className="sidebar-note"><ShieldCheck size={22}/><strong>Your data stays here.</strong><p>Payroll and reports work offline, on this computer.</p></div>
      <div className="sidebar-bottom"><button onClick={toggleTheme} className="theme-button">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}<span>{theme==='light'?'Dark appearance':'Light appearance'}</span></button><div className="local-status"><span/>Local workspace <LockKeyhole size={12}/></div></div>
    </aside>
    <main>
      <div className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><strong>{page}</strong></div><div className="topbar-right"><span className="connection-dot"/>Offline ready<span className="avatar">PD</span></div></div>
      <div className="content">
        <header className="page-header"><div><div className="eyebrow">{page==='Dashboard'?'YOUR COLLEGE, AT A GLANCE':'PAYROLL WORKSPACE'}</div><h1>{page==='Dashboard'?'A clearer view of your payroll.':page==='Payroll'?'Monthly payroll':page==='Employees'?'Your people. All in one place.':page==='Reports'?'Ready to share. Easy to save.':'Make it yours.'}</h1><p>{page==='Dashboard'?'Everything you need for a confident payroll day.':page==='Payroll'?'Review earnings, make adjustments and finalize the month.':page==='Employees'?'Manage staff records and the details behind every payslip.':page==='Reports'?'Accurate reports, generated directly from your selected payroll.':'College details, pay scales and workspace preferences.'}</p></div>{ready&&<div className="month-picker"><span>PAYROLL PERIOD</span><input aria-label="Payroll month" type="month" value={month} onChange={e=>void switchMonth(e.target.value)}/></div>}</header>

        {notice&&<div role="alert" className={'notice '+(notice.error?'error':'success')}><div>{notice.error?<CircleHelp size={19}/>:<Check size={19}/>}</div><div className="notice-text">{notice.text}{notice.open&&<button className="text-button" onClick={()=>window.desktop.openSaved(notice.open!,ok=>{if(!ok)setNotice({text:'The file was saved, but Windows could not open it. Open it from the saved location.',error:true})})}><FolderOpen size={15}/>Open saved file</button>}</div><button className="icon-button" aria-label="Dismiss message" onClick={()=>setNotice(null)}><X size={17}/></button></div>}
        {!ready&&!busy&&<div className="panel empty"><CircleHelp/><h2>Workspace could not open</h2><p>Use the desktop launcher, or retry the connection.</p><button className="primary" onClick={()=>void run('Reconnecting',async()=>{await refresh(month,true);setReady(true)})}>Retry connection</button></div>}

        {ready&&(page==='Dashboard'||page==='Payroll')&&<div className="stat-grid">
          <Stat label="Gross payroll" value={totals.gross} icon={<Wallet size={20}/>} caption="Before deductions"/>
          <Stat label="Total deductions" value={totals.ded} icon={<SlidersHorizontal size={20}/>} caption="CPF, loans & other adjustments"/>
          <Stat label="Net payable" value={totals.net} icon={<ArrowDownToLine size={20}/>} caption={`${rows.length} employees · ${monthLabel(month)}`} accent/>
        </div>}

        {ready&&page==='Dashboard'&&<>
          <section className="welcome-panel"><div className="welcome-art"><Wallet size={42}/></div><div><span className="eyebrow">{locked?'READY FOR YOUR RECORDS':'LET’S GET THIS MONTH READY'}</span><h2>{locked?'Your payroll is finalized.':'A smooth payroll starts here.'}</h2><p>{locked?'Download payslips and statements from the saved monthly figures.':'Review staff salaries, check adjustments and lock the month when you’re ready.'}</p></div><button className="primary" onClick={()=>changePage('Payroll')}>Open payroll <ArrowRight size={17}/></button></section>
          <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>Month at a glance</h2><Badge locked={locked}/></div><div className="overview-row"><span>Employees in this payroll</span><strong>{rows.length}</strong></div><div className="overview-row"><span>Active master records</span><strong>{employees.filter(e=>e.active).length}</strong></div><div className="overview-row"><span>Bank details / net pay to review</span><strong className={issueCount?'amber-text':''}>{issueCount}</strong></div><div className="overview-row"><span>Saved payroll periods</span><strong>{months.length}</strong></div><div className="panel-foot">Changes are saved on this computer. Back up regularly.</div></section><section className="panel"><div className="panel-heading"><h2>Quick actions</h2><span className="muted">Less clicking. More clarity.</span></div><Action icon={<FileText/>} title="Download payslips" description="All employees · PDF document" action={()=>{setScope('all');changePage('Reports')}}/><Action icon={<Upload/>} title="Import salary workbook" description="Bring in your existing college Excel sheet" action={()=>void importWorkbook()}/><Action icon={<Database/>} title="Back up your records" description="Keep a safe copy on another drive" action={()=>void backup()}/></section></div>
          {months.length>0&&<section className="periods"><span>RECENT PERIODS</span>{months.slice(0,6).map(m=><button key={m} onClick={()=>void switchMonth(m)}>{monthLabel(m)}<ArrowRight size={14}/></button>)}</section>}
        </>}

        {ready&&(page==='Employees'||page==='Payroll')&&<section className="panel table-panel">
          <div className="table-toolbar"><div className="search"><Search size={17}/><input aria-label="Search employees" placeholder="Search name, designation or BPS…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="toolbar-actions">{page==='Employees'?<><label className="checkbox-label"><input type="checkbox" checked={includeInactive} onChange={e=>setIncludeInactive(e.target.checked)}/>Show inactive</label><button onClick={()=>void importWorkbook()}><Upload size={16}/>Import Excel</button><button className="primary" onClick={()=>openEditor('employee',{name:'',basic:0,special:0,cpf_member:1,active:1,bank:settings.default_bank})}><Plus size={17}/>Add employee</button></>:<><Badge locked={locked}/><button onClick={()=>void report('salary')}><FileSpreadsheet size={16}/>Export Excel</button><button className="primary" onClick={()=>void report('pdf')}><Download size={16}/>Save PDF</button></>}</div></div>
          {page==='Payroll'&&<div className="table-subbar"><span>{shown.length} employees <span className="divider">/</span> {selected.length} selected</span><div className="inline"><label>Export scope <select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Entire month</option><option value="selected">Selected employees</option></select></label><button className="text-button" onClick={()=>void lockMonth()}><LockKeyhole size={14}/>{locked?'Unlock month':'Review & lock month'}</button></div></div>}
          <div className="table-scroll"><table><thead><tr>{page==='Payroll'&&<th className="select-cell"><input aria-label="Select visible employees" type="checkbox" checked={shown.length>0&&shown.every(r=>selected.includes(r.emp_id))} onChange={e=>setSelected(e.target.checked?Array.from(new Set([...selected,...shown.map(r=>r.emp_id)])):selected.filter(id=>!shown.some(r=>r.emp_id===id)))}/></th>}<th className="name-cell" onClick={()=>toggleSort('name')}>EMPLOYEE {sort.key==='name'?(sort.asc?'↑':'↓'):''}</th><th onClick={()=>toggleSort('bps')}>BPS</th>{page==='Employees'?<><th className="numeric" onClick={()=>toggleSort('basic')}>BASIC PAY</th><th>BANK</th><th>STATUS</th></>:<><th>DAYS</th><th className="numeric" onClick={()=>toggleSort('basic')}>BASIC PAY</th><th className="numeric">ALLOWANCES</th><th className="numeric">ARREARS</th><th className="numeric" onClick={()=>toggleSort('gross')}>GROSS</th><th className="numeric">DEDUCTIONS</th><th className="numeric" onClick={()=>toggleSort('net')}>NET PAY</th></>}<th/></tr></thead><tbody>{shown.map(r=><tr key={r.id||r.emp_id} className={selected.includes(r.emp_id)?'selected':''}>{page==='Payroll'&&<td><input aria-label={'Select '+r.name} type="checkbox" checked={selected.includes(r.emp_id)} onChange={e=>setSelected(e.target.checked?[...selected,r.emp_id]:selected.filter(id=>id!==r.emp_id))}/></td>}<td className="name-cell"><button className="employee-link" onClick={()=>openEditor(page==='Employees'?'employee':'pay',r)}><span className="person-avatar">{String(r.name).split(' ').slice(0,2).map(s=>s[0]).join('')}</span><span><strong>{r.name}</strong><small>{r.designation||r.des||r.category||'Staff member'}</small></span></button></td><td><span className="grade">{r.bps||'—'}</span></td>{page==='Employees'?<><td className="numeric">{money(r.basic)}</td><td>{r.bank||'—'}</td><td><span className={'badge '+(r.active?'green':'neutral')}>{r.active?'Active':'Inactive'}</span></td></>:<><td className="days">{r.worked}<span> / {r.wd}</span></td><td className="numeric">{money(r.basic)}</td><td className="numeric">{money(r.hr+r.conv+r.medl+r.adhoc+r.spec)}</td><td className="numeric">{money(r.arrear)}</td><td className="numeric">{money(r.gross)}</td><td className="numeric deduction">{money(r.gross-r.net)}</td><td className={'numeric net '+(r.net<0?'negative':'')}>{money(r.net)}</td></>}<td><button className="icon-button" aria-label={'Edit '+r.name} onClick={()=>openEditor(page==='Employees'?'employee':'pay',r)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table>{!shown.length&&<div className="empty"><Users size={30}/><h3>{query?'No matching employees':'Your workspace is ready for people'}</h3><p>{query?'Try another name or clear the search.':'Add employees or import your salary workbook to get started.'}</p></div>}</div>
          <div className="table-footer"><span>{page==='Payroll'?'All amounts in PKR · Click an employee to view details':'Master records provide defaults for monthly payroll.'}</span><button className="text-button" onClick={()=>void run('Refreshing',async()=>{await refresh()})}><RefreshCw size={14}/>Refresh</button></div>
        </section>}

        {ready&&page==='Reports'&&<><section className="report-banner"><div><Badge locked={locked}/><h2>{monthLabel(month)}</h2><p>{rows.length} employees · Rs {money(totals.net)} net payable</p></div><label className="field"><span>Include in downloaded reports</span><select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Entire month ({rows.length} employees)</option><option value="selected">Selected employees ({selected.length})</option></select></label></section>{!locked&&<p className="hint"><CircleHelp size={16}/>These reports are drafts. Lock the payroll after reviewing it to preserve the final salary figures.</p>}<div className="report-grid">{reportTypes.map(({kind,title,desc,icon:Icon,tag})=><section className="panel report-card" key={kind}><div className="report-card-top"><div className="report-icon"><Icon size={26}/></div><span className="file-tag">{tag}</span></div><h2>{title}</h2><p>{desc}</p><button onClick={()=>void report(kind)}><Download size={16}/>Save {tag==='EXCEL'?'Excel':tag==='WORD'?'Word':'PDF'}<ArrowRight size={16}/></button></section>)}<section className="panel report-card"><div className="report-card-top"><div className="report-icon violet"><Mail size={26}/></div><span className="file-tag">EMAIL</span></div><h2>Deliver payslips</h2><p>Send an individual PDF to each employee. Requires internet, SMTP setup and a locked month.</p><button disabled={!locked} onClick={()=>void sendEmail()}><Mail size={16}/>Email all payslips<ArrowRight size={16}/></button></section></div><p className="hint"><ShieldCheck size={16}/>Bank statements are documents only. No money is transferred by this application.</p></>}

        {ready&&page==='Settings'&&<><div className="tabs">{['General','BPS scales','Email','Backup & restore'].map(t=><button key={t} className={settingsTab===t?'active':''} onClick={()=>setSettingsTab(t)}>{t}</button>)}</div>
          {(settingsTab==='General'||settingsTab==='Email')&&<section className="panel settings-panel"><div className="panel-heading"><div><h2>{settingsTab==='General'?'College & payroll preferences':'Payslip email settings'}</h2><p>{settingsTab==='General'?'These defaults apply where no monthly override is saved.':'Use your provider’s SMTP credentials. Leave the password blank to keep the saved password.'}</p></div>{settingsTab==='General'&&<button onClick={()=>void run('Saving college logo',async()=>{const pick=await choose('logo');if(pick.cancelled)return;await api('/logo','POST',{ticket:pick.ticket});setNotice({text:'College logo saved. It will appear on new payslips.'})})}><Upload size={16}/>Set logo</button>}</div><div className="form-grid">{Object.keys(labels).filter(k=>settingsTab==='Email'?k.startsWith('smtp_'):!k.startsWith('smtp_')).map(k=><label className="field" key={k}><span>{labels[k]}</span><input type={k==='smtp_password'?'password':['default_working_days','cpf_college_pct','smtp_port'].includes(k)?'number':'text'} value={settings[k]??''} onChange={e=>{setSettings(s=>({...s,[k]:e.target.value}));setSettingsDirty(true)}}/></label>)}</div><div className="settings-footer"><p className="muted">{settingsTab==='General'?'Adhoc allowances are fixed BPS amounts; the payslip wording does not calculate a percentage.':'Email is optional. All other payroll functions work without internet.'}</p><button className="primary" onClick={()=>void run('Saving settings',async()=>{await api('/settings','PUT',settings);await refresh(month,true);setNotice({text:'Settings saved.'})})}><Check size={17}/>Save settings</button></div></section>}
          {settingsTab==='BPS scales'&&<section className="panel"><div className="panel-heading"><div><h2>Fixed allowances by grade</h2><p>Running basic and special allowance are entered per employee.</p></div><button className="primary" onClick={()=>openEditor('scale',{})}><Plus size={16}/>Add grade</button></div><div className="table-scroll"><table><thead><tr>{['BPS','HOUSE RENT','CONVEYANCE','MEDICAL','ADHOC','CPF',''].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{scales.map(s=><tr key={s.bps}>{['bps','hr','conv','medl','adhoc','cpf'].map(k=><td key={k}>{money(s[k])}</td>)}<td><button className="text-button" onClick={()=>openEditor('scale',s)}>Edit grade<ChevronRight size={15}/></button></td></tr>)}</tbody></table></div></section>}
          {settingsTab==='Backup & restore'&&<div className="backup-grid"><section className="panel backup-card"><Database size={32}/><h2>A safe copy, whenever you need it.</h2><p>Save a database backup to another drive. It contains employee records, salary inputs, locked figures and settings, including saved email credentials. Keep it private.</p><button className="primary" onClick={()=>void backup()}><Download size={17}/>Create backup</button><div className="data-location"><span>YOUR LOCAL DATA FOLDER</span><code>{directory}</code></div></section><section className="panel backup-card"><History size={32}/><h2>Move or restore your records.</h2><p>Choose a Payroll Desk database backup. Your current database is backed up automatically before replacement. Saved report files and logo images are separate from the database.</p><button onClick={()=>void restore()}><Upload size={17}/>Restore backup</button></section></div>}
        </>}
        <footer className="workspace-footer"><span>{settings.college_name||'Payroll Desk'}</span><span><ShieldCheck size={13}/>Stored locally · Built for clarity</span></footer>
      </div>
    </main>

    {editor&&<div className="drawer-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)closeEditor()}}><section className="drawer" role="dialog" aria-modal="true" aria-label="Employee details"><div className="drawer-header"><div><div className="eyebrow">{editor.kind==='pay'?monthLabel(month)+' · MONTHLY DETAILS':editor.kind==='scale'?'PAY GRADE':'EMPLOYEE MASTER'}</div><h2>{editor.kind==='scale'?'BPS allowances':editor.data.name||'New employee'}</h2></div><button aria-label="Close editor" className="icon-button" onClick={closeEditor}><X/></button></div><div className="drawer-content">{editor.kind==='pay'&&<div className="form-note"><CircleHelp size={17}/>{locked?'This month is locked. Details are read-only.':'Changes apply only to this month. Employee master records stay unchanged.'}</div>}<fieldset disabled={editor.kind==='pay'&&locked}>
      {editor.kind==='scale'?<><h3>Grade & monthly amounts</h3><div className="form-grid">{[['bps','BPS grade'],['hr','House rent'],['conv','Conveyance'],['medl','Medical'],['adhoc','Adhoc allowance'],['cpf','CPF deduction']].map(([k,l])=>formInput(k,l,'number',{min:0}))}</div></>:<><h3>Personal details</h3><div className="form-grid">{formInput('name','Full name')}{formInput(editor.kind==='pay'?'des':'designation','Designation')}{formInput(editor.kind==='pay'?'dt':'dt_appt','Appointment date')}{formInput('bps','BPS (blank for contract)','number',{min:1,max:30})}{formInput('section','Section')}{editor.kind==='employee'&&formInput('category','Category / group')}</div><h3>Bank & contact details</h3><div className="form-grid">{formInput(editor.kind==='pay'?'acct':'account_no','Bank account number')}{formInput('bank','Bank')}{formInput('email','Email address','email')}{formInput('cpf_no','CPF account number')}<label className="field"><span>CPF member</span><select value={editor.data.cpf_member??1} onChange={e=>edit('cpf_member',Number(e.target.value))}><option value={1}>Yes</option><option value={0}>No</option></select></label>{editor.kind==='employee'&&<label className="field"><span>Employee status</span><select value={editor.data.active??1} onChange={e=>edit('active',Number(e.target.value))}><option value={1}>Active</option><option value={0}>Inactive</option></select></label>}</div><h3>{editor.kind==='pay'?'Attendance & salary inputs':'Default salary'}</h3><div className="form-grid">{editor.kind==='pay'?<>{formInput('wd','Working days','number',{min:1,max:31})}{formInput('worked','Days worked','number',{min:0,max:31})}{payFields.map(([k,l])=>formInput(k,l,'number',k==='arrear'||k==='other'?{}:{min:0}))}</>:<>{formInput('basic','Running basic','number',{min:0})}{formInput('special','Special allowance','number',{min:0})}</>}</div></>}
    </fieldset>{editor.kind==='pay'&&<SalaryPreview row={editor.data}/>}</div><div className="drawer-footer">{editor.kind==='scale'&&editor.data.bps&&<button className="danger-button" onClick={()=>{if(confirm('Delete this BPS grade? Staff without monthly overrides will lose its allowances.'))void run('Deleting grade',async()=>{await api('/scales/'+editor.data.bps,'DELETE');setEditor(null);setDirty(false);await refresh()})}}>Delete grade</button>}<button onClick={closeEditor}>{dirty?'Discard':'Close'}</button>{!(editor.kind==='pay'&&locked)&&<button className="primary" onClick={()=>void saveEditor()}><Check size={17}/>Save changes</button>}</div></section></div>}
    {busy&&<div className="busy-overlay" role="status"><div><LoaderCircle size={27} className="spin"/><strong>{busy}</strong><span>Please wait…</span></div></div>}
  </div>;
}

function Badge({locked}:{locked:boolean}){return <span className={'badge '+(locked?'green':'amber')}>{locked?<LockKeyhole size={12}/>:<span className="tiny-dot"/>}{locked?'Locked':'Draft'}</span>}
function Stat({label,value,icon,caption,accent=false}:{label:string,value:number,icon:React.ReactNode,caption:string,accent?:boolean}){return <section className={'stat-card '+(accent?'accent':'')}><div className="stat-top"><span>{label}</span><div>{icon}</div></div><div className="stat-value"><span>Rs</span>{money(value)}</div><p>{caption}</p></section>}
function Action({icon,title,description,action}:{icon:React.ReactNode,title:string,description:string,action:()=>void}){return <button className="quick-action" onClick={action}><span className="quick-icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={18}/></button>}
function SalaryPreview({row}:{row:Row}){const n=(k:string)=>Number(row[k]||0);const recurring=n('basic')+n('hr')+n('conv')+n('medl')+n('adhoc')+n('spec');const gross=recurring+n('arrear');const leave=n('wd')>0?Math.floor(recurring/n('wd')*Math.max(0,n('wd')-n('worked'))+0.5):0;const ded=(n('cpf_member')?n('cpf'):0)+n('cp_loan')+n('other')+leave;return <div className="salary-preview"><div><span>Gross salary</span><strong>Rs {money(gross)}</strong></div><div><span>Leave deduction</span><strong>Rs {money(leave)}</strong></div><div><span>Total deductions</span><strong>Rs {money(ded)}</strong></div><div className="preview-net"><span>Estimated net pay</span><strong>Rs {money(gross-ded)}</strong></div><small>Preview only. Save to apply changes to the payroll.</small></div>}
